baseURL = "http://demo.gethugothemes.com/bigspring-light/examplesite/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Ignite"
[markup.goldmark.renderer]
unsafe = true
