[[footer_left]]
name = "About Us"
url = "#"
[[footer_middle]]
name = "Pricing"
url = "pricing/"
[[footer_middle]]
name = "Platform"
url = "#"
[[footer_middle]]
name = "Features"
url = "#"
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy/"
[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions/"
[[footer_right]]
name = "FAQ"
url = "faq/"
[[main]]
name = "About"
url = "about/"
weight = "7"
[[main]]
name = "Corporates"
url = "corporates"
weight = "5"
[[main]]
name = "Community"
url = "community/"
weight = "4"
[[main]]
name = "Investors"
url = "investors/"
weight = "3"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Founders"
url = "founders/"
weight = "2"
[[main]]
name = "Blog"
url = "blog/"
weight = "6"
